const money=(n,c="USD")=>new Intl.NumberFormat("en-US",{style:"currency",currency:c,maximumFractionDigits:0}).format(n);
const date=s=>new Date(`${s}T12:00:00Z`).toLocaleDateString("en-US",{month:"short",day:"numeric"});
const time=s=>new Date(s).toLocaleTimeString("en-US",{hour:"numeric",minute:"2-digit"});
const names={TYO:"Tokyo",OSA:"Osaka",NGO:"Nagoya",FUK:"Fukuoka"};
let data={results:[]};
const els=Object.fromEntries(["party","nights","gateway","connections","night","lowest","sort","results","coverage","bestFare","bestParty","scanTime"].map(id=>[id,document.getElementById(id)]));
function verifyLink(x){const q=new URLSearchParams({hl:"en",curr:x.currency||"USD",tfs:`DFW-${x.gateway}-${x.departDate}_${x.gateway}-BKK-${x.onwardDate}`});return `https://www.google.com/travel/flights?${q}`}
function render(){
  let rows=data.results.filter(x=>(els.party.value==="all"||x.partySize==els.party.value)&&(els.nights.value==="all"||x.stopoverNights==els.nights.value)&&(els.gateway.value==="all"||x.gateway===els.gateway.value)&&(els.connections.value==="all"||x.connections<=+els.connections.value)&&(!els.night.checked||x.lateDfw)&&(!els.lowest.checked||x.isNewLow));
  if(els.sort.value==="price")rows.sort((a,b)=>a.total-b.total); else if(els.sort.value==="stops")rows.sort((a,b)=>a.connections-b.connections||a.total-b.total); else rows.sort((a,b)=>b.score-a.score);
  els.coverage.textContent=`${rows.length} matching offers · ${data.coverage?.queriesThisRun||0} itinerary searches in latest run`;
  els.results.innerHTML=rows.length?rows.map((x,i)=>{const a=x.slices[0]?.segments||[],b=x.slices[1]?.segments||[];return `<article class="card ${i===0?'best':''}"><div class="price"><strong>${money(x.perPerson,x.currency)}</strong><small>per person · ${money(x.total,x.currency)} for ${x.partySize}</small>${x.isNewLow?'<span class="badge">NEW LOW</span>':''}</div><div class="legs"><div class="leg"><b>${date(x.departDate)} · DFW → ${names[x.gateway]}</b><p>${a[0]?time(a[0].depart):'—'} departure · ${Math.max(0,a.length-1)} connection${a.length===2?'':'s'}</p><small>${x.lateDfw?'Late departure preferred':'Day departure'}${x.longHaulAtNight?' · Overnight long-haul':''}</small></div><div class="leg"><b>${date(x.onwardDate)} · ${names[x.gateway]} → Bangkok</b><p>${x.stopoverNights} nights in Japan · ${Math.max(0,b.length-1)} connection${b.length===2?'':'s'}</p><small>${x.owner}</small></div></div><div class="actions"><span class="score">${Math.round(x.score)} fit score</span><br><a href="${verifyLink(x)}" target="_blank" rel="noopener">VERIFY FARE ↗</a></div></article>`}).join(""):'<div class="empty">No current offers match these filters. Widen one filter or run another scan.</div>';
}
try{const r=await fetch(`data/results.json?v=${Date.now()}`);data=await r.json();const all=data.results||[];if(all.length){els.bestFare.textContent=money(Math.min(...all.map(x=>x.perPerson)),all[0].currency);els.bestParty.textContent=money(Math.min(...all.map(x=>x.total)),all[0].currency)}els.scanTime.textContent=data.generatedAt?new Date(data.generatedAt).toLocaleString("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}):"Awaiting setup";render()}catch(e){els.coverage.textContent="Could not load fare data."}
for(const id of ["party","nights","gateway","connections","night","lowest","sort"])els[id].addEventListener("change",render);
